PYTESSERACT_PATH = "YOUR TESSARACT PATH"

NUMBER_OF_INACTIVITY = 20 # about 20 minutes for one game

GAME_CLIENT_PATH = "YOUR Hearthstone Beta Launcher.exe PATH"

API_ID = YOUR TELEGRAM API ID

API_HASH = 'YOUR TELEGRAM API HASH'

CONTROL_CHAT_ID = YOUR TELEGRAM CHAT ID

SESSION_NAME = 'YOUR NAME OF FILE .sessions'

MAIN_PY_PATH = 'YOUR PATH TO main.py'
